### ISSUE TITLE
Extension ignores Adobe Launch conditional checks

### ISSUE THREAD

**Issue by TroyGottier** [facebookincubator/reactor-extension-facebook-pixel#35]
Discovered that when this extension is used in Adobe Launch it does not respect the conditionals of any rule utilizing it. 

Steps 
1. activate extension in Adobe Launch 
2. add a rule in launch to fire pageview call using the extensions pageview option, setting a condition to only activate on a specific page url, set the event to fire on "page bottom"
3. build and deploy the rule to your site. 
4. verify that the url you specified has the pixel tag. 

Results
1. Page in the conditional has the pixel tag
2. every other page using the Launch library that rule is made within also implements the pixel tag. 

Problems
1. this implements in China when china is not specified. The call to the pixel is to en_US/fbevents.js which is blocked by the country's firewall. this causes pages to become slow, unresponsive, or blank as the firewall assumes the entire page is trying to access restricted content. 
2. this implements outside of all GDPR solutions that require customer consent to start providing tagging. This in turn then causes all EU pages to break the law by implementing the tag outside of the conditionals. 

Solution 
Disable the extension and implement the pixel via Adobe Launch's custom code. This works as expected and respects the page conditionals even though the extension implements the very same pixel code.

**Comment by TroyGottier** [comment]
So,  what was fix?  Or was this closed for no reason

**Comment by dabramovici** [comment]
> So, what was fix? Or was this closed for no reason

This issue was closed due to the development of this extension being moved to another repo (https://github.com/adobe/reactor-extension-meta-pixel). I will recreate the issue there and mention you there.
